### PR TITLE
[ETFE-3569] Rename isTFESubmission to draftMovementExists

### PR DESCRIPTION
**Pull request by MJCallahanPage**
Note, can't be merged until FE PR is ready. Then can be merged together.

### CODE REVIEW

**Comment by MJCallahanPage** [comment]
test this please

**Review by LewisMitchell — DISMISSED** [review]
Can't run JT's until FE is ready but from a static view it looks good

**Comment by MJCallahanPage** [comment]
I need to push a commit to this to remove the `PORTAL` prefix check too; as that isn't really relevant now the approach for the content has changed. It also won't work where prefix is PORTAL but the draft has expired.

**Review by LewisMitchell — APPROVED** [review]
Approved, needs contract tests

**Pull request merged**
